import { useState, useCallback } from 'react'
import { Plus, Trash2, ChevronDown } from 'lucide-react'
import { uid } from './data'
import type { CommercialSettings as CS, AdditionalCharge } from './types'
function Collapsible({ title, children, open: d = false }: { title: string; children: React.ReactNode; open?: boolean }) { const [open, setOpen] = useState(d); return <div className="ph-collapsible"><button type="button" onClick={() => setOpen(!open)} style={{ width: '100%', textAlign: 'left', padding: '16px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'transparent', border: 'none', fontWeight: 600, fontSize: '15px', color: '#23251d', fontFamily: 'inherit', userSelect: 'none' }}><span>{title}</span><ChevronDown size={14} style={{ color: '#9ea096', transform: open ? 'rotate(180deg)' : 'none', transition: 'transform 0.2s' }} /></button>{open && <div style={{ padding: '0 16px 16px' }}>{children}</div>}</div> }
function Segment({ options, value, onChange }: { options: { value: string; label: string }[]; value: string; onChange: (v: string) => void }) { return <div className="ph-segment">{options.map(o => <button key={o.value} type="button" onClick={() => onChange(o.value)} className={`ph-seg-item ${value === o.value ? 'ph-seg-active' : ''}`}>{o.label}</button>)}</div> }
export function CommercialSettings({ settings, onUpdate }: { settings: CS; onUpdate: (s: CS) => void }) {
  const addCharge = useCallback(() => onUpdate({ ...settings, charges: [...settings.charges, { id: uid(), label: 'Charge', value: 0, taxable: false }] }), [settings])
  const updateCharge = useCallback((id: string, patch: Partial<AdditionalCharge>) => onUpdate({ ...settings, charges: settings.charges.map(c => c.id === id ? { ...c, ...patch } : c) }), [settings])
  const removeCharge = useCallback((id: string) => onUpdate({ ...settings, charges: settings.charges.filter(c => c.id !== id) }), [settings])
  return (
    <Collapsible title="Commercial Settings">
      <div className="ph-field"><label className="ph-label">Payment Terms</label><select value={settings.paymentTerms} onChange={e => onUpdate({ ...settings, paymentTerms: e.target.value })} className="ph-select"><option value="">Select terms</option>{['Due on Receipt', 'Net 7', 'Net 14', 'Net 30', 'Net 60'].map(t => <option key={t} value={t}>{t}</option>)}</select></div>
      <div className="ph-field"><div className="ph-toggle-wrap"><span className="ph-label" style={{ margin: 0 }}>Discount</span><button type="button" onClick={() => onUpdate({ ...settings, discount: { ...settings.discount, enabled: !settings.discount.enabled } })} className={`ph-switch ${settings.discount.enabled ? 'ph-switch-on' : ''}`} /></div>{settings.discount.enabled && <div style={{ marginTop: '10px' }}><div className="ph-field-row"><div className="ph-field"><label className="ph-label">Value</label><input type="number" value={settings.discount.value || ''} onChange={e => onUpdate({ ...settings, discount: { ...settings.discount, value: parseFloat(e.target.value) || 0 } })} min="0" step="0.01" className="ph-input ph-input-compact" /></div><div className="ph-field"><label className="ph-label">Type</label><Segment options={[{ value: 'percentage', label: '%' }, { value: 'flat', label: 'Flat' }]} value={settings.discount.type} onChange={v => onUpdate({ ...settings, discount: { ...settings.discount, type: v as 'percentage' | 'flat' } })} /></div></div><div className="ph-field" style={{ marginTop: '10px' }}><label className="ph-label">Timing</label><Segment options={[{ value: 'beforeTax', label: 'Before Tax' }, { value: 'afterTax', label: 'After Tax' }]} value={settings.discount.timing} onChange={v => onUpdate({ ...settings, discount: { ...settings.discount, timing: v as 'beforeTax' | 'afterTax' } })} /></div></div>}</div>
      <div className="ph-field"><div className="ph-toggle-wrap"><span className="ph-label" style={{ margin: 0 }}>VAT</span><button type="button" onClick={() => onUpdate({ ...settings, vat: { ...settings.vat, enabled: !settings.vat.enabled } })} className={`ph-switch ${settings.vat.enabled ? 'ph-switch-on' : ''}`} /></div>{settings.vat.enabled && <div style={{ marginTop: '10px' }}><label className="ph-label">Rate (%)</label><input type="number" value={settings.vat.rate || ''} onChange={e => onUpdate({ ...settings, vat: { ...settings.vat, rate: parseFloat(e.target.value) || 0 } })} min="0" step="0.01" className="ph-input ph-input-compact" /></div>}</div>
      <div className="ph-field"><div className="ph-toggle-wrap"><span className="ph-label" style={{ margin: 0 }}>WHT</span><button type="button" onClick={() => onUpdate({ ...settings, wht: { ...settings.wht, enabled: !settings.wht.enabled } })} className={`ph-switch ${settings.wht.enabled ? 'ph-switch-on' : ''}`} /></div>{settings.wht.enabled && <div style={{ marginTop: '10px' }}><div className="ph-field-row"><div className="ph-field"><label className="ph-label">Rate</label><input type="number" value={settings.wht.rate || ''} onChange={e => onUpdate({ ...settings, wht: { ...settings.wht, rate: parseFloat(e.target.value) || 0 } })} min="0" step="0.01" className="ph-input ph-input-compact" /></div><div className="ph-field"><label className="ph-label">Unit</label><Segment options={[{ value: 'percentage', label: '%' }, { value: 'flat', label: 'Flat' }]} value={settings.wht.unit} onChange={v => onUpdate({ ...settings, wht: { ...settings.wht, unit: v as 'percentage' | 'flat' } })} /></div></div></div>}</div>
      <div className="ph-field"><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}><span className="ph-label" style={{ margin: 0 }}>Additional Charges</span><button type="button" onClick={addCharge} className="ph-btn ph-btn-sm">+ Add</button></div>{settings.charges.map(c => <div key={c.id} className="ph-charge-row"><input type="text" value={c.label} onChange={e => updateCharge(c.id, { label: e.target.value })} placeholder="Label" className="ph-input ph-input-compact" style={{ flex: 2, minWidth: '120px' }} /><input type="number" value={c.value || ''} onChange={e => updateCharge(c.id, { value: parseFloat(e.target.value) || 0 })} min="0" step="0.01" className="ph-input ph-input-compact" style={{ flex: 1, minWidth: '80px' }} /><span onClick={() => updateCharge(c.id, { taxable: !c.taxable })} className={`ph-charge-status ${c.taxable ? 'ph-charge-tax' : 'ph-charge-nontax'}`}>{c.taxable ? 'Taxable' : 'Non-taxable'}</span><button type="button" onClick={() => removeCharge(c.id)} style={{ width: '36px', height: '36px', padding: 0, border: 'none', background: 'none', borderRadius: '4px', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#9ea096', fontSize: '18px', flexShrink: 0 }}>&#10005;</button></div>)}</div>
    </Collapsible>
  )
}
